# Wait 10 milliseconds to check files under the current directory
scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ/âœ—"
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red) "
format = "$symbol "
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[conda]
format = '\[[$symbol$environment](dimmed green)\]'
disabled = false

[python]
symbol = "ğŸ"
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[shell]
disabled = false
fish_indicator = "ğŸŸ"
bash_indicator = "ğŸš"

[directory]
truncation_symbol = "[..]/"
truncation_length = 3
truncate_to_repo = true

[cmd_duration]
format = '\[ğŸ•“[$duration]($style)\]'

[jobs]
symbol = "ğŸ‘·"

[[battery.display]]
threshold = 10
style = "bold red"
